export default [
  {
    id: '1',
    name: 'Mission 1',
    description: 'Description for Mission 1',
    assigned: false,
    location: 'Location 1',
    value: 100,
    tags: ['tag1', 'tag2'],
    createdDate: Date.now(),
    updatedDate: Date.now(),
    expiresDate: Date.now() + 86400000,
    createdBy: 'User 1',
    status: 'active',
    risk: 'baixo',
    isFeatured: false,
    isNearUser: true,
  },
  {
    id: '2',
    name: 'Mission 2',
    description: 'Description for Mission 2',
    assigned: true,
    location: 'Location 2',
    value: 200,
    tags: ['tag3', 'tag4'],
    createdDate: Date.now(),
    updatedDate: Date.now(),
    expiresDate: Date.now() + 172800000,
    createdBy: 'User 2',
    status: 'completed',
    risk: 'médio',
    isFeatured: true,
    isNearUser: false,
  },
  {
    id: '3',
    name: 'Mission 3',
    description: 'Description for Mission 3',
    assigned: false,
    location: 'Location 3',
    value: 300,
    tags: ['tag5', 'tag6'],
    createdDate: Date.now(),
    updatedDate: Date.now(),
    expiresDate: Date.now() + 259200000,
    createdBy: 'User 3',
    status: 'active',
    risk: 'alto',
    isFeatured: false,
    isNearUser: true,
  }
]