export const chats = [
  {
    id: 'c1',
    name: 'Carlos Mendez',
    initials: 'CM',
    avatarColor: '#3b82f6',
    isOnline: true,
    lastMessage: 'Consegui completar a missão! 🎉',
    lastTime: '10:42',
    unreadCount: 2,
    messages: [
      { id: 'm1', from: 'other', text: 'Oi! Vi que você também está na missão Operação Lixão.', time: '10:30' },
      { id: 'm2', from: 'user', text: 'Sim! Você já foi ao ponto de coleta?', time: '10:32' },
      { id: 'm3', from: 'other', text: 'Fui ontem. Dica: leva luvas extras!', time: '10:35' },
      { id: 'm4', from: 'user', text: 'Bom saber, valeu! 🙏', time: '10:38' },
      { id: 'm5', from: 'other', text: 'Consegui completar a missão! 🎉', time: '10:42' },
      { id: 'm6', from: 'other', text: 'R$ 380 caiu na conta, haha', time: '10:43' },
    ],
  },
  {
    id: 'c2',
    name: 'Ana Paula',
    initials: 'AP',
    avatarColor: '#ec4899',
    isOnline: false,
    lastMessage: 'Tem alguma missão perto do centro?',
    lastTime: '09:15',
    unreadCount: 0,
    messages: [
      { id: 'm1', from: 'other', text: 'Olá! Somos do mesmo grupo de hunters?', time: '09:00' },
      { id: 'm2', from: 'user', text: 'Acho que sim! Vi seu perfil na missão Tutoria Jr.', time: '09:05' },
      { id: 'm3', from: 'other', text: 'Isso! Você já fez alguma missão de tutoria antes?', time: '09:10' },
      { id: 'm4', from: 'user', text: 'Já! São bem tranquilas. Te ajudo com as dúvidas.', time: '09:12' },
      { id: 'm5', from: 'other', text: 'Tem alguma missão perto do centro?', time: '09:15' },
    ],
  },
  {
    id: 'c3',
    name: 'Grupo Hunters SP',
    initials: 'GH',
    avatarColor: '#7c3aed',
    isOnline: true,
    lastMessage: 'Você: Galera, temos 3 missões novas hoje!',
    lastTime: 'Ontem',
    unreadCount: 0,
    messages: [
      { id: 'm1', from: 'other', text: 'Bom dia hunters! 🔥', time: 'Ontem 08:00' },
      { id: 'm2', from: 'other', text: 'Missão no mercadão está paga! R$ 250', time: 'Ontem 08:05' },
      { id: 'm3', from: 'user', text: 'Galera, temos 3 missões novas hoje!', time: 'Ontem 08:10' },
    ],
  },
  {
    id: 'c4',
    name: 'Roberto Silva',
    initials: 'RS',
    avatarColor: '#10b981',
    isOnline: false,
    lastMessage: 'Ok, até amanhã então!',
    lastTime: 'Ontem',
    unreadCount: 0,
    messages: [
      { id: 'm1', from: 'other', text: 'Você toparia dividir uma missão comigo?', time: 'Ontem 15:00' },
      { id: 'm2', from: 'user', text: 'Qual missão você está pensando?', time: 'Ontem 15:02' },
      { id: 'm3', from: 'other', text: 'Operação Jardim Limpo. Paga R$ 600 dividido.', time: 'Ontem 15:05' },
      { id: 'm4', from: 'user', text: 'Gostei! Mas preciso verificar minha agenda.', time: 'Ontem 15:08' },
      { id: 'm5', from: 'other', text: 'Ok, até amanhã então!', time: 'Ontem 15:10' },
    ],
  },
  {
    id: 'c5',
    name: 'Suporte iHunt',
    initials: 'iH',
    avatarColor: '#f60',
    isOnline: true,
    lastMessage: 'Sua conta foi verificada com sucesso! ✅',
    lastTime: 'Seg',
    unreadCount: 1,
    messages: [
      { id: 'm1', from: 'other', text: 'Olá! Sou o assistente do iHunt. Como posso ajudar?', time: 'Seg 09:00' },
      { id: 'm2', from: 'user', text: 'Quero verificar minha conta.', time: 'Seg 09:05' },
      { id: 'm3', from: 'other', text: 'Claro! Já iniciamos o processo. Aguarde um instante.', time: 'Seg 09:06' },
      { id: 'm4', from: 'other', text: 'Sua conta foi verificada com sucesso! ✅', time: 'Seg 09:10' },
    ],
  },
]

export const botReplies = [
  'Entendido! 👍',
  'Ótimo! Posso te ajudar com mais alguma coisa?',
  'Ha! Bom saber disso! 😄',
  'Interessante! Vou verificar isso.',
  'Vamos nessa! 💪',
  'Legal! Combinado então.',
  'Ok! Me avisa quando souber mais.',
  'Show de bola! 🎯',
  'Que missão boa! Vale a pena tentar.',
]
